### ISSUE TITLE
On pressing back button App crashes

### ISSUE THREAD

**Issue by natarajnattu** [PonnamKarthik/FlutterYoutube#19]
Hi,

Here is the log when i press back button from the youtube page

any advice?

E/AndroidRuntime( 9945): Process: com.example.challenges, PID: 9945
E/AndroidRuntime( 9945): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=111, result=0, data=null} to activity {com.example.challenges/com.example.challenges.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
E/AndroidRuntime( 9945): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4382)
E/AndroidRuntime( 9945): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4426)
E/AndroidRuntime( 9945): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime( 9945): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
E/AndroidRuntime( 9945): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 9945): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 9945): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
E/AndroidRuntime( 9945): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9945): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime( 9945): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
E/AndroidRuntime( 9945): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
E/AndroidRuntime( 9945): 	at com.cueclad.flutterrazorpay.FlutterRazorpayPlugin.onActivityResult(FlutterRazorpayPlugin.java:75)
E/AndroidRuntime( 9945): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime( 9945): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime( 9945): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime( 9945): 	at android.app.Activity.dispatchActivityResult(Activity.java:7305)
E/AndroidRuntime( 9945): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4378)

**Comment by natarajnattu** [comment]
I think the plugin somehow interacting other plugins in the project in my case its razorpay.

**Comment by natarajnattu** [comment]
the response code for intent is changed 111 to some other number, cuz the other packages are picking the response code
