### ISSUE TITLE
No implementation found for method playYoutubeVideo on channel PonnamKarthik/flutter_youtube

### ISSUE THREAD

**Issue by johnny-stevie** [PonnamKarthik/FlutterYoutube#54]
I get this error when trying to start a simple Youtube video

`Performing hot reload...                                                
Reloaded 3 of 675 libraries in 1,720ms.
E/flutter ( 6127): [ERROR:flutter/shell/common/shell.cc(178)] Dart Error: Unhandled exception:
E/flutter ( 6127): MissingPluginException(No implementation found for method playYoutubeVideo on channel PonnamKarthik/flutter_youtube)
E/flutter ( 6127): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter ( 6127): <asynchronous suspension>
E/flutter ( 6127): #1      FlutterYoutube.playYoutubeVideoById (package:flutter_youtube/flutter_youtube.dart:97:14)
E/flutter ( 6127): #2      _YouTubeShowResults.build (package:quick_song/search_results_widget.dart:19:24)
E/flutter ( 6127): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
E/flutter ( 6127): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
E/flutter ( 6127): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 6127): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
E/flutter ( 6127): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter ( 6127): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 6127): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 6127): #12     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
E/flutter ( 6127): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter ( 6127): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter ( 6127): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter ( 6127): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter ( 6127): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 6127): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 6127): #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
E/flutter ( 6127): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 6127): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 6127): #28     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
E/flutter ( 6127): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 6127): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 6127): #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
E/flutter ( 6127): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter ( 6127): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 6127): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 6127): #38     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
E/flutter ( 6127): #39     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
E/flutter ( 6127): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter ( 6127): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter ( 6127): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 6127): #44     Element.rebuild (p`

source code:
 `Widget build(BuildContext context){
      return Container(
        child:
        FlutterYoutube.playYoutubeVideoById(
          apiKey: "API_KEY",
          videoId: widget.searchId,
          autoPlay: true, //default falase
          fullScreen: true //default false
        )
    )
}`

**Comment by fabiot21** [comment]
Same issue

**Comment by draftin1** [comment]
I get this same issue. Has anyone found a solution?
